# Generated by Django 3.0.8 on 2020-07-23 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.OneToOneField(default=1, on_delete=models.SET(1), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
